#162685666 Users can comment on articles
andela/Ah-backend-guardians pull request #25
Opened 2019-01-18 07:50 UTC by Opio-Emmanuel-Omona

#### What does this PR do?
This PR enables only authenticated users to comment on an article(s).

#### Description of Task to be completed?
Authenticated users are able to comment on articles that have been published. The users are able to perform all the CRUD functionality on the comments of the articles.
Available endpoints include
```
GET api/<slug>/comments/         Gets all comments for a particular article
```
```
POST api/<slug>/comments/         Creates a comment for a particular article
```
```
GET api/<slug>/comments/<id>/         Get a specific comment of an article
```
```
PUT api/<slug>/comments/<id>/         Update a specific comment of an article
```
```
DELETE api/<slug>/comments/<id>/         Delete a specific comment of an article
```
```
POST api/<slug>/comments/<id>/thread/         Comment on a comment
```
```
GET api/<slug>/comments/<id>/thread/         Get entire thread of a comment
```

#### How should this be manually tested?
Run the following commands in your terminal.

- `git clone https://github.com/andela/Ah-backend-guardians.git`
- `cd Ah-backend-guardians`
- `virtualenv venv`
- `source venv/bin/activate`
- `git checkout ft-comment-on-articles-162685666`
- `python3 manage.py runserver`

Alternatively, you can test the app using the Heroku link below
https://ah-backend-guardians-sta-pr-25.herokuapp.com/

Next open POSTMAN and begin to test out the end points listed above.
The data required in a POST and PUT is in the form
```
{
	"body":  ""
}
```

Note: You must be logged in to access the endpoints and atleast one article should be present in your database.

#### What are the relevant pivotal tracker stories?
#162685666

#### Screenshots (if appropriate)
This shows a GET all comments for an article
![image](https://user-images.githubusercontent.com/26769886/51371844-5d46f680-1b0c-11e9-8539-da61a6f7ca3f.png)

2019-01-22 08:47 UTC, fahadmak requested changes
it is not necessary for you to have input ` parent: id` key-value pair in your post. yet you have the parent id in the urls you pass for creating a thread comment

<img width="1552" alt="screen shot 2019-01-22 at 11 39 33 am" src="https://user-images.githubusercontent.com/13882936/51522679-fd698c00-1e3a-11e9-86c8-2e874006fd77.png">

2019-01-22 09:20 UTC, Opio-Emmanuel-Omona commented
@fahadmak I have worked on the "parent" key issue.
<img width="1137" alt="screen shot 2019-01-22 at 12 18 17 pm" src="https://user-images.githubusercontent.com/26769886/51524832-04df6400-1e40-11e9-963b-50d04fd42345.png">

2019-01-22 11:58 UTC, moseskamira approved these changes
LGTM. I have reviewed it both locally and on Heroku too.

2019-01-22 11:59 UTC, fahadmak commented
LGTM

2019-01-22 11:59 UTC, fahadmak approved these changes

2019-01-22 12:23 UTC, archbishop12 commented
@Opio-Emmanuel-Omona Ensure one cannot delete/update a comment he/she did not create.

2019-01-22 12:31 UTC, archbishop12 commented
@Opio-Emmanuel-Omona Can threaded comments be updated or deleted???

2019-01-22 12:38 UTC, archbishop12 commented
@Opio-Emmanuel-Omona Run pep8 on the files you added to ensure there are no violations.

2019-01-22 12:40 UTC, archbishop12 commented on authors/apps/comments/views.py
> +            message = 'Article does not exist'
@Opio-Emmanuel-Omona Return a dictionary here to maintain consistency through out the entire application.

2019-01-22 12:42 UTC, archbishop12 commented on authors/apps/comments/views.py
> +                message = 'Comment does not exist'
```suggestion
                message = {'message': 'Comment does not exist'}
```

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +            message = 'Article does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +                message = 'Comment does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +            message = 'Article does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +                message = 'Comment does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +            message = 'Article does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:43 UTC, archbishop12 commented on authors/apps/comments/views.py
> +                message = 'Comment does not exist'
@Opio-Emmanuel-Omona Same applies here.

2019-01-22 12:45 UTC, archbishop12 commented on authors/apps/comments/views.py
> +            message = 'Article does not exist'
@Opio-Emmanuel-Omona Some of these messages seem to appear multiple times. Could you avoid repeating yourself.

2019-01-22 12:54 UTC, fahadmak requested changes
Add docstring comments in your tests and comments endpoint

2019-01-22 14:42 UTC, Opio-Emmanuel-Omona commented
@archbishop12 

> @Opio-Emmanuel-Omona Can threaded comments be updated or deleted???
Yes, they can, They have IDs and are deleted/updated just like any other comment. 
```
DELETE api/<slug>/comments/<id>/
```

> @Opio-Emmanuel-Omona Ensure one cannot delete/update a comment he/she did not create.
Resolved: Only the author of the comment can delete/update the comment


> @Opio-Emmanuel-Omona Run pep8 on the files you added to ensure there are no violations.
Resolved: All files follow the pep8 guidelines

2019-01-22 14:59 UTC, Opio-Emmanuel-Omona commented
> Add docstring comments in your tests and comments endpoint

Resolved

2019-01-22 15:49 UTC, fahadmak approved these changes
LGTM

2019-01-22 17:16 UTC, archbishop12 commented
@Opio-Emmanuel-Omona When one tries to delete a threaded comment using this route `api/<slug>/comments/<id>/` and there exists a non threaded comment with the same `id` both are deleted. Look into this.

2019-01-23 05:51 UTC, archbishop12 approved these changes
LGTM @Opio-Emmanuel-Omona I am merging this.

2019-01-23 05:52 UTC, merged