#162685671 User can view profiles
andela/Ah-backend-guardians pull request #26
Opened 2019-01-21 11:46 UTC by fahadmak

#### What does this PR do?
PR enables users should be able to see the list and profiles of existing authors
#### Description of Task to be completed?
A logged in/authenticated user should be able to see the list and profiles of existing authors. 
#### How should this be manually tested?
Before testing run these commands in cmd

`git clone https://github.com/andela/Ah-backend-guardians.git`

`cd Ah-backend-guardians`

`git checkout ft-view-all-profiles-162685671`

`virtualenv env`

`. env/bin/activate`

`pip install -r requirements.txt`

1.  Create a postgres database and a `.env` file in your root directory and add the following configurations.
```
SECRET_KEY=andela_sjdndkjghdf78872

DB_NAME=your_database_name

DB_USER=database_user

DB_PASSWORD=database_password

DB_HOST=127.0.0.1

ALLOWED_HOSTS=.localhost, .herokuapp.com

EMAIL_PORT=587

EMAIL_HOST_USER = gauthorshaven@gmail.com

EMAIL_HOST_PASSWORD = guardiansauthors
```
2. Open Postman and type `http://localhost:8000/api/profiles/` in url text box. Select GET in methods drop down then click `SEND` button
#### What are the relevant pivotal tracker stories?
[#162685671](https://www.pivotaltracker.com/story/show/162685671)
#### Screenshots (if appropriate)
![screen shot 2019-01-21 at 2 44 57 pm](https://user-images.githubusercontent.com/13882936/51472680-35b19180-1d8b-11e9-8715-b1ca02570076.png)

2019-01-21 14:02 UTC, VivianDoreen approved these changes
LGTM

2019-01-22 05:05 UTC, BarnaTB requested changes
Great work @fahadmak! Just add those docstrings as in the comments and all should be well.

2019-01-22 05:05 UTC, BarnaTB commented on authors/apps/profiles/tests/test_views.py
> +    def test_get_all_user_profiles(self):
Please a docstring comment for this test.

2019-01-22 05:05 UTC, BarnaTB commented on authors/apps/profiles/views.py
> +class ListProfileView(generics.ListAPIView):
Please add a docstring for this class.

2019-01-22 07:29 UTC, BarnaTB approved these changes
LGTM!

2019-01-22 07:41 UTC, archbishop12 approved these changes
@fahadmak I am merging this.

2019-01-22 07:53 UTC, merged