feat(Favorite Article): implement the Favorite Article functionality
andela/Ah-backend-guardians pull request #34
Opened 2019-01-23 19:04 UTC by moseskamira

#### What Does This PR Do?
This PR enables a user to favorite an article

#### Link To Pivotal Tracker Story
#162685669

#### How Should This Be Manually Tested
Fetching the branch 'ft-favorite-article-162685669' onto your local machine

#### Run the App

- Fetch the Article of interest by using the url: http://127.0.0.1:8000/api/articles/slug/

- Using POST method, append the word 'favorite' on to the above url to Favorite the Article: url should appear as below; http://127.0.0.1:8000/api/articles/slug/favorite/

- Using the PUT method on the same url, the Article shall be Unfavorited

#### NOTE
You do not need to pass anything in the body

Snapshots

2019-01-24 07:08 UTC, tomuhenry approved these changes
LGTM, I think the PR is running the way it is required to.

2019-01-24 07:29 UTC, Opio-Emmanuel-Omona approved these changes
LGTM

2019-01-24 07:44 UTC, VivianDoreen requested changes
Could you kindly use descriptive message when favouriting an article? Instead of returning the article, you could return "You have favourited the article"

![image](https://user-images.githubusercontent.com/41106626/51662374-b0192600-1fc4-11e9-80ca-51ba08002533.png)

2019-01-24 09:42 UTC, moseskamira commented
> Could you kindly use descriptive message when favouriting an article? Instead of returning the article, you could return "You have favourited the article"
> 
> ![image](https://user-images.githubusercontent.com/41106626/51662374-b0192600-1fc4-11e9-80ca-51ba08002533.png)

Worked upon your requested changes, could you please review and do the needful?
<img width="423" alt="screen shot 2019-01-24 at 12 42 08 pm" src="https://user-images.githubusercontent.com/42971167/51669428-874d5c80-1fd5-11e9-9dad-ac14e5f1d18d.png">

2019-01-24 09:44 UTC, VivianDoreen approved these changes

2019-01-28 07:03 UTC, archbishop12 commented on authors/apps/articles/views.py
> +    def put(self, request, **kwargs):
@moseskamira Implement the feedback given to you during the review session.

2019-01-28 07:45 UTC, archbishop12 commented on authors/apps/articles/views.py
> +        if (counter == 1):
@moseskamira Is this if statement necessary. You refactor the logic here.

2019-01-28 07:47 UTC, archbishop12 commented on authors/apps/articles/views.py
> +            serializer = self.serializer_class(data={}, partial=True)
@moseskamira Look at the logic and make sure it si consistent. Ensure you don't *repeat yourself*.

2019-01-30 05:29 UTC, archbishop12 commented
@moseskamira When one tries to favourite an article they have to do it twice. Fix this flaw in your code.

2019-01-30 08:20 UTC, merged