#162685674 Users can search through articles
andela/Ah-backend-guardians pull request #42
Opened 2019-01-30 09:52 UTC by myrdstom

**What does this PR do?**

This PR enables a user to search an article by keyword, title, username or tag

Any user should be able to perform a search, whether authenticated or not

Before testing run these commands in the terminal

`git clone https://github.com/andela/Ah-backend-guardians.git`

`cd Ah-backend-guardians`

`git checkout ft-add-search-functionality-162685674`

`virtualenv --python=python3 venv`

`source venv/bin/activate`

pip install -r requirements.txt

Create a Postgres database and a .env file in your root directory and add the following configurations.

```

SECRET_KEY=andela_sjdndkjghdf78872

DB_NAME=your_database_name

DB_USER=database_user

DB_PASSWORD=database_password

DB_HOST=127.0.0.1

ALLOWED_HOSTS=.localhost, .herokuapp.com

EMAIL_PORT=587

EMAIL_HOST_USER = gauthorshaven@gmail.com

EMAIL_HOST_PASSWORD = guardiansauthors

WORD_LENGTH = 5

WPM = 200

```

Copy and paste this link into postman `http://127.0.0.1:8000/api/articles/`  and add the sample data below to create an article
```
{
	
    "title": "Africa Power and Equipment",
    "body": "Africa Power and Equipment Limited is a local mid-sized company incorporated in Uganda    in 2013 and has over sixty years of combined 
               industry experience with an aim of providing solutions to the unreliable power supply in the region. We ride on a team of staff with
               a wealth of experience in a wide range of critical aspects necessary to achieve your goals.",
    "description": "Power Produing Company",

    "tags":["Power", "Generators", "Trafing"]
}
```
To test searching all fields, input the following link into postman `http://127.0.0.1:8000/api/articles/?search=[desired search key word]`

To test searching by title, input the following link into postman `http://127.0.0.1:8000/api/articles/?title=[desired search key word]`

To test searching by username, input the following link into postman `http://127.0.0.1:8000/api/articles/?author__username=[desired search key word]`

To test searching by tag, input the following link into postman `http://127.0.0.1:8000/api/articles/?tags=[desired search key word]`

An article, combination of articles  or no article will be returned depending on the intupted search parameters.

**Screenshot of an existing returned article**

<img width="974" alt="screen shot 2019-01-30 at 11 01 31 am" src="https://user-images.githubusercontent.com/30922279/51966793-8f4a4800-247e-11e9-89bf-4609d0cb185e.png">

**Screenshot or a query for an article that does not exist**

<img width="974" alt="screen shot 2019-01-30 at 11 01 44 am" src="https://user-images.githubusercontent.com/30922279/51966812-9bcea080-247e-11e9-8260-8d5ea7b70678.png">

**Relevant pivotal tracker stories?**

[#162685674](https://www.pivotaltracker.com/n/projects/2232496)

2019-01-30 13:37 UTC, tomuhenry approved these changes
LGTM...

2019-01-30 14:03 UTC, fahadmak approved these changes
LGTM

2019-01-30 18:45 UTC, archbishop12 commented on authors/apps/articles/filters.py
> +        fields = ['title', 'author__username', 'tags']
@myrdstom Any reason why the filter for username one should provide the exact value or else it will nothing. Any reasons why or else it should be like the other searches and return the related values.

2019-01-31 04:46 UTC, myrdstom commented on authors/apps/articles/filters.py
> +        fields = ['title', 'author__username', 'tags']
From what I had seen in a few API's filter by username necessitated an exact value. But if the user experience can be better if we  filter by an approximation of  the username, I will make the necessary adjustment

2019-01-31 06:55 UTC, fahadmak requested changes
Why does it search when you don't provide any query parameter please look into that

2019-01-31 07:22 UTC, VivianDoreen requested changes
Though most of the search criteria are successful, search by username is not functioning as expected. It is returning all the available articles. Could you please re-test the endpoint for search by username and confirm what am saying, then do the needful. 

@myrdstom, the Acceptance Criteria for your task is "Any user (authenticated or not) should be able to search for articles on our platform", Could you look into this because when I was reviewing your PR, a non authenticated user was unable to search for the articles.

![image](https://user-images.githubusercontent.com/41106626/52039398-7789c700-2545-11e9-9dc4-96b14bbdb0cb.png)

2019-03-05 09:55 UTC, fahadmak approved these changes
LGTM

2019-03-05 11:31 UTC, VivianDoreen approved these changes
LGTM

2019-03-05 11:31 UTC, VivianDoreen commented on authors/apps/articles/views.py
> +from .renderers import ArticleJSONRenderer, ArticlesJSONRenderer, ArticlesLikesJSONRenderer
line too long (91 > 79 characters) 
The above statement (from .renderers ... )does not conform to pep8 standards. Kindly use pep8 to conform to pep8 standards.

2019-03-05 11:31 UTC, VivianDoreen commented on authors/apps/articles/views.py
> +)
line too long (101 > 79 characters)
The above statement (from .serializers ... )does not conform to pep8 standards, Kindly use pep8 to conform to pep8 standards.

2019-03-05 11:31 UTC, VivianDoreen commented on authors/apps/articles/tests/test_articles.py
> +    def test_search_by_key_word(self):
Expected 1 blank line, found 0, According to pep8 standards, Kindly rectify that.

2019-03-05 12:10 UTC, merged